# Generated by Django 5.1.4 on 2025-01-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.TextField(blank=True),
        ),
    ]
