# Generated by Django 5.1.4 on 2025-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.TextField(blank=True),
        ),
    ]
