# Generated by Django 5.1.4 on 2025-02-11 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_subject_options_subject_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.AddField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
