# Generated by Django 5.1.4 on 2025-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profile_pics/default.jpg', null=True, upload_to='images/profile_pics'),
        ),
    ]
