# Generated by Django 5.0.7 on 2025-03-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_exercise_question_exam_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, to='courses.question'),
        ),
    ]
