# Generated by Django 5.0.7 on 2025-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_answer_question_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='questions',
            field=models.ManyToManyField(blank=True, to='courses.question'),
        ),
    ]
