# Generated by Django 5.0.7 on 2025-03-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_exercise_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.module'),
        ),
    ]
