# Generated by Django 5.1.4 on 2025-03-06 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_exercise_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
