# Generated by Django 5.1.4 on 2025-03-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_exercisequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.exercise'),
        ),
        migrations.DeleteModel(
            name='ExerciseQuestion',
        ),
    ]
