# Generated by Django 5.1.4 on 2025-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='description',
            new_name='question_description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
