# Generated by Django 5.1.4 on 2025-03-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_rename_description_exercise_question_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.module'),
        ),
    ]
