# Generated by Django 5.0.7 on 2025-04-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_exercise_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/exercise_files'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/exercise_images'),
        ),
    ]
