# Generated by Django 5.0.7 on 2025-04-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_exercise_file_exercise_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='file',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.CreateModel(
            name='ExerciseAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/exercise_files/answer_files')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_files', to='courses.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAnswerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/exercise_images/answer_images')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_images', to='courses.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/exercise_files/question_files')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_files', to='courses.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseQuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/exercise_images/question_images')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='courses.exercise')),
            ],
        ),
    ]
