# Generated by Django 5.1.4 on 2025-04-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_exercise_file_remove_exercise_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseanswerimage',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercisequestionfile',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercisequestionimage',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='files/exercise_files/answer_files'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/exercise_images/answer_images'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='files/exercise_files/question_files'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/exercise_images/question_images'),
        ),
        migrations.DeleteModel(
            name='ExerciseAnswerFile',
        ),
        migrations.DeleteModel(
            name='ExerciseAnswerImage',
        ),
        migrations.DeleteModel(
            name='ExerciseQuestionFile',
        ),
        migrations.DeleteModel(
            name='ExerciseQuestionImage',
        ),
    ]
