# Generated by Django 5.1.4 on 2025-04-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_exerciseanswerimage_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='answer_image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question_image',
        ),
    ]
