# Generated by Django 5.1.4 on 2025-04-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_remove_exercise_answer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
