# Generated by Django 5.1.4 on 2025-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_exercise_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ManyToManyField(blank=True, to='courses.exam'),
        ),
    ]
