# Generated by Django 5.0.7 on 2025-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_answer_question_alter_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True or False'), ('ESSAY', 'Essay')], default='ESSAY', max_length=200),
        ),
    ]
