# Generated by Django 5.0.7 on 2025-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
