# Generated by Django 5.0.7 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_true',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
