# Generated by Django 5.0.7 on 2025-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_question_score_studentexamattempt_studentexamanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamanswer',
            name='boolean_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
