# Generated by Django 5.1.4 on 2025-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_studentexamanswer_boolean_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
