# Generated by Django 5.1.4 on 2025-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_exam_is_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
