# Generated by Django 5.1.4 on 2025-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_studentcoursecompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Academic year in format YYYY-YYYY (e.g. 2024-2025)', max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='StudentCourseCompletion',
        ),
    ]
