# Generated by Django 5.1.4 on 2025-05-30 08:59

from django.db import migrations


def migrate_existing_enrollments(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    StudentCourseEnrollment = apps.get_model('courses', 'StudentCourseEnrollment')
    AcademicYear = apps.get_model('courses', 'AcademicYear')

    # Get current academic year
    current_year = AcademicYear.objects.filter(is_current=True).first()

    # For each course
    for course in Course.objects.all():
        # For each student in the course
        for student in course.students.all():
            # Create enrollment record
            StudentCourseEnrollment.objects.create(
                student=student,
                course=course,
                academic_year=current_year
            )

def reverse_migration(apps, schema_editor):
    StudentCourseEnrollment = apps.get_model('courses', 'StudentCourseEnrollment')
    StudentCourseEnrollment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_studentcourseenrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_enrollments, reverse_migration),
    ]
