# Generated by Django 5.1.4 on 2025-05-30 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_migrate_existing_enrollments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year_enrollment', to='courses.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseenrollment',
            unique_together={('student', 'course', 'academic_year')},
        ),
    ]
