# Generated by Django 5.1.4 on 2025-05-30 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_studentcourseenrollment_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='courses.studentcourseenrollment')),
            ],
        ),
    ]
