# Generated by Django 5.1.4 on 2025-05-30 09:04

from django.db import migrations

def migrate_existing_completions(apps, schema_editor):
    # If you have an existing StudentCourseCompletion model with a different structure,
    # you would migrate data from it here.
    # Since we don't have evidence of existing completion records, this is a placeholder.
    pass

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_studentcoursecompletion'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_completions, reverse_migration),
    ]
