# Generated by Django 5.1.4 on 2025-05-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_migrate_existing_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='courses.studentcourseenrollment'),
        ),
    ]
