# Generated by Django 5.1.4 on 2025-05-30 09:12

from django.db import migrations


def link_exam_attempts_to_enrollments(apps, schema_editor):
    StudentExamAttempt = apps.get_model('courses', 'StudentExamAttempt')
    StudentCourseEnrollment = apps.get_model('courses', 'StudentCourseEnrollment')

    # For each exam attempt
    for attempt in StudentExamAttempt.objects.all():
        # Find the corresponding enrollment
        enrollment = StudentCourseEnrollment.objects.filter(
            student=attempt.student,
            course=attempt.exam.course
        ).first()

        if enrollment:
            attempt.enrollment = enrollment
            attempt.save()


def reverse_migration(apps, schema_editor):
    StudentExamAttempt = apps.get_model('courses', 'StudentExamAttempt')

    for attempt in StudentExamAttempt.objects.all():
        attempt.enrollment = None
        attempt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_studentexamattempt_enrollment'),
    ]

    operations = [
        migrations.RunPython(link_exam_attempts_to_enrollments, reverse_migration),
    ]
