# Generated by Django 5.1.4 on 2025-05-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_link_exam_attempts_to_enrollments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together={('enrollment', 'exam')},
        ),

    ]
