# Generated by Django 5.0.7 on 2025-05-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_alter_studentexamattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='student',
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='courses.studentcourseenrollment'),
        ),
    ]
