# Generated by Django 5.1.4 on 2025-06-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_remove_student_field_from_studentexamattempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattemptsreset',
            name='student',
        ),
        migrations.AddField(
            model_name='studentexamattemptsreset',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts_resets', to='courses.studentcourseenrollment'),
        ),
    ]
