# Generated by Django 5.1.4 on 2025-06-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_remove_studentexamattemptsreset_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
