# Generated by Django 5.1.4 on 2025-06-11 19:01

from django.db import migrations


def set_academic_years(apps, schema_editor):
    Exam = apps.get_model('courses', 'Exam')
    StudentExamAttempt = apps.get_model('courses', 'StudentExamAttempt')
    AcademicYear = apps.get_model('courses', 'AcademicYear')

    current_year = AcademicYear.objects.filter(is_current=True).first()
    if not current_year and AcademicYear.objects.exists():
        current_year = AcademicYear.objects.order_by('-start_date').first()

    for exam in Exam.objects.filter(academic_year__isnull=True):
        attempt = StudentExamAttempt.objects.filter(exam=exam,
                                                    is_finalized=True).order_by('-started_at').first()
        if attempt and hasattr(attempt, 'enrollment') and attempt.enrollment.academic_year:
            exam.academic_year = attempt.enrollment.academic_year
        elif current_year:
            exam.academic_year = current_year
        else:
            raise Exception(f"Cannot set academic year for exam {exam.id}: {exam.title}")
        exam.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_exam_academic_year'),
    ]

    operations = [
        migrations.RunPython(set_academic_years),
    ]
