# Generated by Django 5.1.4 on 2025-06-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_set_academic_year_for_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.academicyear'),
        ),
    ]
