# Generated by Django 5.2.3 on 2025-07-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_alter_exam_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('completed', 'Ολοκληρώθηκε'), ('failed', 'Απέτυχε'), ('refunded', 'Επιστροφή χρημάτων')], default='pending', max_length=20)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='courses.studentcourseenrollment')),
            ],
        ),
    ]
