# Generated by Django 5.2.3 on 2025-07-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_subject_price_coursepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
