# Generated by Django 5.2.3 on 2025-07-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_remove_subject_price_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
