# Generated by Django 5.2.3 on 2025-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_alter_coursepayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
