# Generated by Django 5.0.7 on 2025-07-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepayment',
            old_name='transaction_id',
            new_name='old_transaction_id',
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.transaction'),
        ),
    ]
