# Generated by Django 5.0.7 on 2025-07-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_migrate_payments_to_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepayment',
            name='old_transaction_id',
        ),
        migrations.RemoveField(
            model_name='coursepayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='coursepayment',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='coursepayment',
            name='status',
        ),
    ]
