# Generated by Django 5.2.4 on 2025-08-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_remove_coursepayment_old_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Mark this exam as the final exam for the course.'),
        ),
    ]
